"""add kb_entries table

Revision ID: ff1f0ab0c5f8
Revises: e11bb6c9d4b8
Create Date: 2026-04-13 18:57:43.423819

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ff1f0ab0c5f8'
down_revision: Union[str, Sequence[str], None] = 'e11bb6c9d4b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kb_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dify_document_id', sa.String(length=128), nullable=False),
    sa.Column('dify_dataset_id', sa.String(length=128), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=128), nullable=True),
    sa.Column('tags', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('original_source', sa.String(length=512), nullable=True),
    sa.Column('source_url', sa.String(length=512), nullable=True),
    sa.Column('material_id', sa.String(length=255), nullable=True),
    sa.Column('campus', sa.String(length=64), nullable=True),
    sa.Column('original_filename', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dify_document_id')
    )
    op.create_index(op.f('ix_kb_entries_title'), 'kb_entries', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_kb_entries_title'), table_name='kb_entries')
    op.drop_table('kb_entries')
    # ### end Alembic commands ###
